name: "Multi Evenet Pipeline work flow" # NAme of the pipeline
on: 
    push: # Event: Whenever push is made to the repo on the master branch
        branches:
            - master
            - test

    schedule: # schedule a action
        - cron: "3 15 * * 2,4" # schedule on time 3 on tuesday and thursday

    pull_request: # Event: Whenever a pull request is made to the repo
        branches:
            - master
        types: 
            - closed
            - opened

    workflow_dispatch:

jobs:
    on-push: # JOb name 1
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps: # steps to be exicuted in job
            - name: "Running on master/test push" # step 1
              run: echo "Running on master/test push"

    on-pull-request: # Job Name 2
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps: # steps to be exicuted in job
            - name: "Running on pull request" # step 1
              run: echo "Running on pull request"

    on-pull-request-opened:
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on pull request opened"
              run: echo "Running on pull request opened"

    on-pull-request-closed:
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        runs-on: ubuntu-latest
        steps: # steps to be exicuted in job
            - name: "Running on pull request closed" # step 1
              run: echo "Running on pull request closed"

    on-workflow-dispatch: # Job 3
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps: # steps to be exicuted in job
            - name: "Running on workflow dispatch" # step 1
              run: echo "Running on workflow dispatch"

    on-schedule: # Job 3
        if: github.event_name == 'schedule'
        runs-on: ubuntu-latest
        steps: # steps to be exicuted in job
            - name: "Running on Schedule" # step 1
              run: echo "Running on Schedule"